In [1]:
import numpy as np
import pandas as pd
df = pd.read_csv('../rsidis_bigtable_pass0p1.csv')
df.tail(2)

,run,ebeam,target,hms_p,hms_th,shms_p,shms_th,run_type,x,Q2,...,normyield,normyield_err,ctmean,ctsigma,fan_mean,fan_stdev,boil_corr,IHWP,start_time,stop_time
1553,25602,2.231,LH2,-1.723,19.0,-1.86,18.5,HEE,-999.0,-999.0,...,-999.0,-999.0,-999.0,-999.0,43.8607,1.66719,1.003659,OUT,2025-09-03 06:45:40,2025-09-03 06:51:14
1554,25603,2.231,LH2,-1.723,19.0,-1.82,18.5,HEE,-999.0,-999.0,...,-999.0,-999.0,-999.0,-999.0,43.8128,1.71256,1.003753,OUT,2025-09-03 06:52:15,2025-09-03 07:00:36

## Clean up

In [2]:
df.replace(-999, np.nan, inplace=True);

## New Columns

In [3]:
df.columns

Index(['run', 'ebeam', 'target', 'hms_p', 'hms_th', 'shms_p', 'shms_th',
       'run_type', 'x', 'Q2', 'z', 'thpq', 'BCM1_Q', 'BCM1_I', 'BCM2_Q',
       'BCM2_I', 'BCM4A_Q', 'BCM4A_I', 'BCM4B_Q', 'BCM4B_I', 'BCM4C_Q',
       'BCM4C_I', 'h_esing_Eff', 'h_hadron_Eff', 'p_esing_Eff', 'p_hadron_Eff',
       'ps1', 'ps2', 'ps3', 'ps4', 'ps5', 'ps6', 'comp_livetime',
       'electr_deadtime', 'coin', 'randoms', 'ransubcoin', 'normyield',
       'normyield_err', 'ctmean', 'ctsigma', 'fan_mean', 'fan_stdev',
       'boil_corr', 'IHWP', 'start_time', 'stop_time'],
      dtype='str')

In [4]:
#df.iloc[0:5, 0:38]
#df.columns
df.insert(loc=37, column='normyield_new', value=df['ransubcoin']* (df['boil_corr'] / (df['BCM2_Q']*df['h_esing_Eff']*df['p_hadron_Eff']*df['comp_livetime'])))
#df['ransubcoin'] / (df['BCM2_Q'])

In [5]:
#df.iloc[:,35:40].head(100)
#df[['run', 'target', 'normyield_new', 'normyield']][(df['x']!=-999) & (df['target']=='Al')]
#df[['run', 'target', 'normyield_new', 'normyield', 'boil_corr']][((df['run_type']=='PI-SIDIS') | (df['run_type']=='PI+SIDIS')) & (df['hms_p']<0)] # & (df['boil_corr'].isna())]

## Filters

In [6]:
pd.set_option('display.max_rows', None)
print(df[['ebeam', 'x', 'Q2', 'z', 'thpq', 'hms_p']][(df['x']!=-999) & (df['target']=='Al')]
      .drop_duplicates()
      .sort_values(by=['z']))

        ebeam     x   Q2     z  thpq  hms_p
1435  10.6716  0.25  3.3  0.36   2.0  3.642
457    8.5831  0.25  3.3  0.50   2.0 -1.531
636    8.5831  0.25  3.3  0.50   2.0  1.531
1292  10.6716  0.25  3.3  0.50   2.0 -3.642

In [7]:
pd.set_option('display.max_rows', None)
print(df[['target', 'ebeam', 'x', 'Q2', 'z', 'thpq', 'hms_p', 'run_type', 'run']][(df['target']=='C') & (df['ebeam']==10.6716) & (df['z']==0.5) & (df['thpq']==-0.8) & (df['run_type']=="PI-SIDIS")]
      .drop_duplicates()
      .sort_values(by=['z']))

     target    ebeam     x   Q2    z  thpq  hms_p  run_type    run
1111      C  10.6716  0.25  3.3  0.5  -0.8 -3.642  PI-SIDIS  25096
1112      C  10.6716  0.25  3.3  0.5  -0.8 -3.642  PI-SIDIS  25097
1113      C  10.6716  0.25  3.3  0.5  -0.8 -3.642  PI-SIDIS  25098
1114      C  10.6716  0.25  3.3  0.5  -0.8 -3.642  PI-SIDIS  25099

In [8]:
pd.set_option('display.max_rows', None)
print(df[['target', 'ebeam', 'x', 'Q2', 'z', 'thpq', 'hms_p', 'run_type', 'run']][(df['target']=='C') & (df['ebeam']==10.6716) & (df['shms_p']==-3.632) & (df['shms_th']==7.51) & (df['run_type']=="PI-SIDIS")]
      .drop_duplicates()
      .sort_values(by=['z']))

     target    ebeam     x   Q2    z  thpq  hms_p  run_type    run
1111      C  10.6716  0.25  3.3  0.5  -0.8 -3.642  PI-SIDIS  25096
1112      C  10.6716  0.25  3.3  0.5  -0.8 -3.642  PI-SIDIS  25097
1113      C  10.6716  0.25  3.3  0.5  -0.8 -3.642  PI-SIDIS  25098
1114      C  10.6716  0.25  3.3  0.5  -0.8 -3.642  PI-SIDIS  25099

In [9]:
pd.set_option('display.max_rows', None)
df_pim = (df[['target', 'ebeam', 'x', 'Q2', 'z', 'thpq', 'run_type']][(df['target']!='Dummy') & (df['ebeam']==10.6716) & (df['run_type']=="PI-SIDIS")]
            .drop_duplicates()      
            .sort_values(by=['z', 'target', 'thpq']))
df_pip = (df[['target', 'ebeam', 'x', 'Q2', 'z', 'thpq', 'run_type']][(df['target']!='Dummy') & (df['ebeam']==10.6716) & (df['run_type']=="PI+SIDIS")]
            .drop_duplicates()      
            .sort_values(by=['z', 'target', 'thpq']))
df_pim.head()
df_pip.head()

     target    ebeam     x   Q2     z  thpq  run_type
1321      C  10.6716  0.25  3.3  0.36   2.0  PI+SIDIS
1323     Cu  10.6716  0.25  3.3  0.36   2.0  PI+SIDIS
1305    LD2  10.6716  0.25  3.3  0.36   2.0  PI+SIDIS
1499    LH2  10.6716  0.25  3.3  0.36  -0.2  PI+SIDIS
1313    LH2  10.6716  0.25  3.3  0.36   2.0  PI+SIDIS

In [ ]:
#df_pim.to_csv('rpr1_pim_settings.csv', index=False)
#df_pip.to_csv('rpr1_pip_settings.csv', index=False)

In [11]:
print(df[['target', 'ebeam', 'x', 'Q2', 'z', 'thpq', 'run_type']][(df['target']!='Dummy') & (df['ebeam']==10.6716) & (df['run_type']=="PI+SIDIS")]
            .drop_duplicates()      
            .sort_values(by=['z', 'target', 'thpq']))

     target    ebeam     x   Q2     z  thpq  run_type
1321      C  10.6716  0.25  3.3  0.36   2.0  PI+SIDIS
1323     Cu  10.6716  0.25  3.3  0.36   2.0  PI+SIDIS
1305    LD2  10.6716  0.25  3.3  0.36   2.0  PI+SIDIS
1499    LH2  10.6716  0.25  3.3  0.36  -0.2  PI+SIDIS
1313    LH2  10.6716  0.25  3.3  0.36   2.0  PI+SIDIS
1292     Al  10.6716  0.25  3.3  0.50   2.0  PI+SIDIS
1009      C  10.6716  0.25  3.3  0.50  -0.8  PI+SIDIS
1284      C  10.6716  0.25  3.3  0.50   2.0  PI+SIDIS
1342      C  10.6716  0.25  3.3  0.50   5.2  PI+SIDIS
1015     Cu  10.6716  0.25  3.3  0.50  -0.8  PI+SIDIS
1287     Cu  10.6716  0.25  3.3  0.50   2.0  PI+SIDIS
1346     Cu  10.6716  0.25  3.3  0.50   5.2  PI+SIDIS
989     LD2  10.6716  0.25  3.3  0.50  -0.8  PI+SIDIS
1269    LD2  10.6716  0.25  3.3  0.50   2.0  PI+SIDIS
1335    LD2  10.6716  0.25  3.3  0.50   5.2  PI+SIDIS
997     LH2  10.6716  0.25  3.3  0.50  -0.8  PI+SIDIS
1275    LH2  10.6716  0.25  3.3  0.50   2.0  PI+SIDIS
1329    LH2  10.6716  0.25  3.3  0.50   5.2  PI+SIDIS
1355    LH2  10.6716  0.25  3.3  0.50   8.5  PI+SIDIS
959       C  10.6716  0.25  3.3  0.67  -0.8  PI+SIDIS
1261      C  10.6716  0.25  3.3  0.67   2.0  PI+SIDIS
965      Cu  10.6716  0.25  3.3  0.67  -0.8  PI+SIDIS
1264     Cu  10.6716  0.25  3.3  0.67   2.0  PI+SIDIS
941     LD2  10.6716  0.25  3.3  0.67  -0.8  PI+SIDIS
1244    LD2  10.6716  0.25  3.3  0.67   2.0  PI+SIDIS
947     LH2  10.6716  0.25  3.3  0.67  -0.8  PI+SIDIS
1251    LH2  10.6716  0.25  3.3  0.67   2.0  PI+SIDIS
932       C  10.6716  0.25  3.3  0.90  -0.8  PI+SIDIS
1237      C  10.6716  0.25  3.3  0.90   2.0  PI+SIDIS
937      Cu  10.6716  0.25  3.3  0.90  -0.8  PI+SIDIS
1241     Cu  10.6716  0.25  3.3  0.90   2.0  PI+SIDIS
912     LD2  10.6716  0.25  3.3  0.90  -0.8  PI+SIDIS
1221    LD2  10.6716  0.25  3.3  0.90   2.0  PI+SIDIS
921     LH2  10.6716  0.25  3.3  0.90  -0.8  PI+SIDIS
1226    LH2  10.6716  0.25  3.3  0.90   2.0  PI+SIDIS
1429     Cu  10.6716   NaN  NaN   NaN   NaN  PI+SIDIS
1428    LH2  10.6716   NaN  NaN   NaN   NaN  PI+SIDIS

## Archived

In [12]:
#df.duplicates(subset=['ebeam', 'x', 'Q2', 'z', 'thpq', 'run_type'])['run']